from fastapi import FastAPI, Depends, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, Response
from sqlalchemy.orm import Session
from sqlalchemy import desc

from models import (
    Base, engine, get_db,
    Patient, Case, CarePlan, PatientGamification,
    PatientListOut, GamificationState, GamificationSave
)

app = FastAPI(
    title="MedCare — Patient Recovery Dashboard API",
    description="Backend API for patient-facing recovery gamification, tracking, and care plans",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allow any frontend origin for local prototype
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/", include_in_schema=False)
def root():
    """Health check / root route — prevents 404 on GET /"""
    return JSONResponse({
        "status": "ok",
        "service": "MedCare Patient Recovery API",
        "version": "1.0.0",
        "docs": "/docs",
        "message": "Patient dashboard frontend runs on http://localhost:5174"
    })

@app.get("/favicon.ico", include_in_schema=False)
def favicon():
    """Suppress favicon 404 — return empty 204 No Content"""
    return Response(status_code=204)

@app.on_event("startup")
def startup_event():
    # Automatically create the patient_gamification table in shared medcare.db if not exists
    Base.metadata.create_all(bind=engine)

@app.get("/api/patients/all", response_model=list[PatientListOut])
def list_patients(db: Session = Depends(get_db)):
    """List all registered patients (useful for selecting a patient profile in the demo)."""
    return db.query(Patient).order_by(Patient.name).all()

@app.get("/api/patients/{patient_id}/plan")
def get_patient_plan(patient_id: str, db: Session = Depends(get_db)):
    """Retrieve the latest care plan for the patient."""
    case = (
        db.query(Case)
        .filter(Case.patient_id == patient_id)
        .order_by(desc(Case.created_at))
        .first()
    )
    if not case:
        raise HTTPException(status_code=404, detail="No hospital discharge records found for this patient.")
    
    if not case.care_plan:
        raise HTTPException(
            status_code=404,
            detail="Your care plan is currently being generated by the clinical system. Please check back shortly!"
        )
    
    cp = case.care_plan
    p = case.patient_id
    ent = case.extracted_entities or {}
    pat=(db.query(Patient).filter(Patient.id == p).first())

    # print("**************************************************************************",pat,"**************************************************************************")
        
    return {
        "case_id": case.id,
        "patient_id": case.patient_id,
        "patient_name": pat.name if p else None,
        "patient_age": pat.age if p else None,
        "patient_sex": pat.sex if p else None,
        "patient_weight": pat.weight_kg if pat else None,
        "allergies": pat.allergies or [],
        "plan_data": cp.plan_data,
        "approved": cp.approved,
        "approved_by": cp.approved_by,
        "approved_at": cp.approved_at,
        "generated_at": cp.generated_at,
    }

@app.get("/api/patients/{patient_id}/gamification", response_model=GamificationState)
def get_gamification(patient_id: str, db: Session = Depends(get_db)):
    """Retrieve or initialize the patient's recovery gamification state."""
    # Verify patient exists
    p = db.query(Patient).filter(Patient.id == patient_id).first()
    if not p:
        raise HTTPException(status_code=404, detail="Patient not found")
        
    state = db.query(PatientGamification).filter(PatientGamification.patient_id == patient_id).first()
    if not state:
        # Initialize default state in DB
        state = PatientGamification(
            patient_id=patient_id,
            xp=0,
            level=1,
            streak=0,
            longest_streak=0,
            last_active_date=None,
            badges=[],
            task_log={},
            vital_log=[]
        )
        db.add(state)
        db.commit()
        db.refresh(state)
        
    return state

@app.post("/api/patients/{patient_id}/gamification", response_model=GamificationState)
def save_gamification(patient_id: str, data: GamificationSave, db: Session = Depends(get_db)):
    """Save the updated recovery checklist and gamification state."""
    state = db.query(PatientGamification).filter(PatientGamification.patient_id == patient_id).first()
    if not state:
        state = PatientGamification(patient_id=patient_id)
        db.add(state)
        
    state.xp = data.xp
    state.level = data.level
    state.streak = data.streak
    state.longest_streak = data.longest_streak
    state.last_active_date = data.last_active_date
    state.badges = data.badges
    state.task_log = data.task_log
    state.vital_log = data.vital_log
    
    db.commit()
    db.refresh(state)
    return state

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="127.0.0.1", port=8001, reload=True)
